

import React, { useState, useCallback } from 'react';
// FIX: Corrected the import path to use the consolidated geminiService from AIFeaturesMFE.
import { geminiService } from '../../../AIFeaturesMFE'; // Shared service
import type { MedicalRecordEntry } from '../../types';
// FIX: Corrected import path to central icons library
import { Sparkles, Copy, AlertTriangle } from '../../../../components/icons';

interface AISummaryGeneratorProps {
    notes: MedicalRecordEntry[];
}

const AISummaryGenerator: React.FC<AISummaryGeneratorProps> = ({ notes }) => {
    const [summary, setSummary] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [copied, setCopied] = useState(false);

    const handleGenerateSummary = useCallback(async () => {
        setIsLoading(true);
        setError(null);
        setSummary(null);
        try {
            const result = await geminiService.summarizeMedicalNotes(notes);
            setSummary(result);
        } catch (err) {
            setError('Failed to generate summary. Please try again.');
            console.error(err);
        } finally {
            setIsLoading(false);
        }
    }, [notes]);

    const handleCopy = () => {
        if (summary) {
            navigator.clipboard.writeText(summary);
            setCopied(true);
            setTimeout(() => setCopied(false), 2000);
        }
    };

    return (
        <div className="p-4 bg-slate-50 border border-slate-200 rounded-lg">
            <div className="flex flex-col sm:flex-row justify-between sm:items-center gap-4">
                <h3 className="text-lg font-semibold text-slate-800 flex items-center gap-2">
                    <Sparkles size={20} className="text-indigo-500" />
                    AI-Powered Summary
                </h3>
                <button
                    onClick={handleGenerateSummary}
                    disabled={isLoading || notes.length === 0}
                    className="inline-flex items-center justify-center gap-2 px-4 py-2 border border-transparent text-sm font-medium rounded-md shadow-sm text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 disabled:bg-slate-300 disabled:cursor-not-allowed transition-colors"
                >
                    {isLoading ? (
                        <>
                            <svg className="animate-spin -ml-1 mr-3 h-5 w-5 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                                <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                                <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                            </svg>
                            Generating...
                        </>
                    ) : (
                        'Generate Summary'
                    )}
                </button>
            </div>

            {error && (
                <div className="mt-4 p-3 bg-red-100 text-red-700 border border-red-200 rounded-lg text-sm">
                    {error}
                </div>
            )}

            {summary && (
                <div className="mt-4 p-4 bg-white rounded-md border border-slate-200 relative">
                    <button
                        onClick={handleCopy}
                        className="absolute top-2 right-2 px-2 py-1 text-xs font-semibold text-slate-600 bg-slate-100 hover:bg-slate-200 rounded-md"
                    >
                        <Copy size={14} className="inline-block mr-1" />
                        {copied ? 'Copied!' : 'Copy'}
                    </button>
                    <div className="prose prose-sm max-w-none text-slate-800 whitespace-pre-wrap">
                        {summary}
                    </div>
                </div>
            )}
            
            <div className="mt-4 flex items-start gap-2 p-3 bg-amber-50 text-amber-800 border-l-4 border-amber-400 text-xs">
                 <AlertTriangle size={16} className="flex-shrink-0 mt-0.5" />
                 <div>
                    <strong>Disclaimer:</strong> This summary is generated by an AI and may contain inaccuracies. Always verify critical information with the original source documents.
                 </div>
            </div>
        </div>
    );
};

export default AISummaryGenerator;